all:
  hosts:
    raspberrypi00:
      ansible_host: # Fill in
    raspberrypi01:
      ansible_host: # Fill in
  children:
    masters:
      hosts:
        raspberrypi01:
    minions:
      hosts:
        raspberrypi00:
        raspberrypi01:
